# Generated by Django 5.2.4 on 2025-07-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('Stap_admin', 'Stap_admin'), ('superadmin', 'Super Admin')], default='user', max_length=20),
        ),
    ]
