# Generated by Django 5.2.1 on 2025-06-23 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_stylist_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='sessionhistory',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionhistory',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_images/'),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='OutfitAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100)),
                ('image', models.ImageField(upload_to='outfit_images/')),
                ('title', models.CharField(max_length=100)),
                ('colors', models.JSONField()),
                ('description', models.TextField()),
                ('advice', models.TextField()),
                ('bullet_advice', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
